<template>
  <div class="flex-1" @click="handleChatClick">
    <div
      class="chat mb-2"
      v-for="(message, index) in chatHistoryDisplay"
      :key="message.api_message_id || `local-${index}`"
      :class="{
        'chat-start': message.role === 'assistant' || message.role === 'system',
        'chat-end': message.role === 'user',
      }"
    >
      <div
        class="chat-bubble mb-2"
        :class="{
          'chat-bubble-primary': message.role === 'assistant',
          'chat-bubble-accent': message.role === 'developer',
          'chat-bubble-info': message.role === 'system',
        }"
        v-html="getDisplayableMessageContent(message)"
      ></div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useGeneralStore } from '../stores/generalStore'
import type {
  ChatMessage,
  AppChatMessageContentPart,
} from '../stores/openAIStore'
import { messageMarkdown } from '../utils/markdown'
import { storeToRefs } from 'pinia'

const generalStore = useGeneralStore()
const { chatHistory } = storeToRefs(generalStore)

const chatHistoryDisplay = computed(() => {
  return [...chatHistory.value].reverse().filter(message => {
    const isGenerallyDisplayableRole =
      message.role === 'assistant' ||
      message.role === 'system' ||
      message.role === 'developer' ||
      message.role === 'user'

    if (!isGenerallyDisplayableRole) {
      return false
    }

    if (message.role === 'assistant') {
      if (typeof message.content === 'string') {
        if (message.content.trim() === '') {
          return false
        }
      } else if (Array.isArray(message.content)) {
        if (message.content.length === 0) {
          return false
        }
        const allPartsAreEffectivelyEmptyText = message.content.every(
          part =>
            part.type === 'app_text' && (!part.text || part.text.trim() === '')
        )
        if (allPartsAreEffectivelyEmptyText) {
          return false
        }
      } else if (message.content == null) {
        return false
      }
    }

    return true
  })
})

const openImageWithSystemViewer = (absoluteFilePath: string) => {
  if (!absoluteFilePath) {
    console.warn('Cannot open image: No absolute path provided.')
    return
  }
  const correctedPath = absoluteFilePath.replace(/\\/g, '/')
  console.log(
    `Requesting to open image with system viewer at OS path: ${correctedPath}`
  )
  window.ipcRenderer
    .invoke('electron:open-path', { target: correctedPath })
    .then(result => {
      if (!result.success) {
        console.error(
          "Failed to open image via IPC ('electron:open-path'):",
          result.message
        )
      }
    })
    .catch(err =>
      console.error("Error invoking 'electron:open-path' for image:", err)
    )
}

const getDisplayableMessageContent = (message: ChatMessage): string => {
  if (typeof message.content === 'string') {
    return messageMarkdown(message.content)
  } else if (Array.isArray(message.content)) {
    let combinedHtml = ''
    for (const part of message.content as AppChatMessageContentPart[]) {
      if (part.type === 'app_text' && part.text) {
        if (part.text.trim() !== '') {
          combinedHtml += messageMarkdown(part.text) + '<br/>'
        }
      } else if (
        part.type === 'app_generated_image_path' &&
        part.path &&
        part.absolutePathForOpening
      ) {
        const imageSrcForDisplay = `alice-image://${part.path}`
        combinedHtml += `
          <img 
            src="${imageSrcForDisplay}" 
            alt="Generated by Alice" 
            class="max-w-xs md:max-w-sm rounded-lg my-2 cursor-pointer shadow-lg generated-alice-image" 
            data-absolute-path="${part.absolutePathForOpening}"
            title="Click to open image"
          />
          <br/>`
      } else if (part.type === 'app_image_uri' && part.uri) {
        combinedHtml += `
          <img 
            src="${part.uri}" 
            alt="User provided image" 
            class="max-w-xs md:max-w-sm rounded-lg my-2 shadow-lg" 
            title="User provided image"
          />
          <br/>`
      }
    }
    return combinedHtml.endsWith('<br/>') && combinedHtml.length > 5
      ? combinedHtml.slice(0, -5)
      : combinedHtml
  }
  return messageMarkdown('Error: Unable to display message content.')
}

const handleChatClick = (event: MouseEvent) => {
  let targetElement = event.target as HTMLElement

  if (
    targetElement.tagName === 'IMG' &&
    targetElement.classList.contains('generated-alice-image')
  ) {
    const absoluteImagePath = targetElement.getAttribute('data-absolute-path')
    if (absoluteImagePath) {
      openImageWithSystemViewer(absoluteImagePath)
      event.preventDefault()
      return
    } else {
      console.warn(
        "Clicked generated image has no 'data-absolute-path' attribute."
      )
    }
  }

  for (
    let i = 0;
    i < 3 && targetElement && targetElement !== event.currentTarget;
    i++
  ) {
    if (targetElement.tagName === 'A') {
      const href = targetElement.getAttribute('href')
      if (
        href &&
        (href.startsWith('http://') ||
          href.startsWith('https://') ||
          href.startsWith('mailto:'))
      ) {
        console.log(
          `Clicked on a standard link: ${href}. Electron should handle opening.`
        )
        return
      }
    }
    if (targetElement.parentElement) {
      targetElement = targetElement.parentElement
    } else {
      break
    }
  }
}
</script>
